### ISSUE TITLE
If the object name is Japanese, an error occurs with `@app.handlers.s3()`.

### ISSUE THREAD

**Issue by youyo** [serverless-operations/jeffy#21]
I tried this sample code.

```
from jeffy.framework import get_app


app = get_app()


@app.handlers.s3()
def handler(event, context):
    print(event['key'])
    print(event['bucket_name'])
    print(event['body'])
```

It worked fine when the file `test.txt` was uploaded to s3, but the An error occurred when I uploaded a file called `テスト.txt`.

```
[ERROR] ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
Traceback (most recent call last):
  File "/var/task/jeffy/handlers/s3.py", line 59, in wrapper
    raise e
  File "/var/task/jeffy/handlers/s3.py", line 40, in wrapper
    response = s3.get_resource().get_object(Bucket=bucket, Key=key)
  File "/var/task/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

A permission error occurs, but it looks like a different error.
If the object name is in Japanese, need to decode the URL.

**Comment by marcy-terui** [comment]
Thank you for your reporting and patch !!
It is merged and released at [v1.1.1](https://github.com/serverless-operations/jeffy/releases/tag/v1.1.1).
